from os import path

WORK_DIR = path.abspath(path.curdir)
MODELS_DIR = path.join(WORK_DIR, "models")
BEST_MODEL_PATH = path.join(MODELS_DIR, "best.h5")
MODELS_HISTORY_DIR = path.join(MODELS_DIR, "history")
MODELS_LOG_PATH = path.join(MODELS_HISTORY_DIR, "log.db")

MEMORY_SIZE = 10_000
MIN_MEMORY_SIZE = 1_024
STATES_UNTIL_FITTING = 100
BATCH_SIZE = 64
MEMORY_SAMPLE_SIZE = MIN_MEMORY_SIZE // 2
LEARNING_RATE = 0.1
SAVE_INTERVAL = 50

TRAINING_REQUEST = bytes(0)
TRAINING_RESPONSE = b"train"
PREDICT_REQUEST  = bytes(1)
PREDICT_RESPONSE = b"pdict"

HOST_PORT = 1995
NUMBER_OF_CONNECTIONS = 10